language: python
python:
  '3.6'
install:
  pip install tox-travis coverage codecov mock pycrypto
script:
  python setup.py test
script:
  tox
script:
  coverage run --source=cryptiles -m unittest discover -s tests/
after_success:
  codecov